# The env variable `TAPEAGENTS_LLM_TOKEN` should be set. Add the following line to your ~/.bashrc or ~/.zshenv:
# export TAPEAGENTS_LLM_TOKEN=`cat /mnt/llmd/data/.llmd_glide_token`
_target_: tapeagents.llms.TrainableLLM
model_name: /mnt/llmd/results/exps/gontiern/llama31_8b_instruct_gff_teacher_traces_bs32_lr1e4/intermediate/448_merged_only
stream: false
use_cache: false
context_size: 128000
base_url: https://snow-research-tapes-448_merged_only.job.toolkit-sp.yul201.service-now.com
parameters:
  temperature: 1.0
  max_tokens: 4096 # we need to use max_tokens (instead of 'max_completion_tokens') when using TGI
