[build-system]
requires = ["setuptools >= 67.6.1"]
build-backend = "setuptools.build_meta"

[project]
name = "TapeAgents"
version = "0.0.3"
description = "TapeAgents framework for building, tuning and evaluating LLM Agents"
authors = [
  {name="Dzmitry Bahdanau", email="dzmitry.bahdanau@servicenow.com"},
  {name="Oleh Shliazhko", email="oleh.shliazhko@servicenow.com"},
  {name="Alexandre Piché", email="alexandre.piche@servicenow.com"},
]
readme = "README.md"
requires-python = ">= 3.10"
dynamic = ["dependencies"]

[tool.setuptools.dynamic]
dependencies = {file = ["requirements.txt"]}

[tool.setuptools.packages.find]
include = ["tapeagents*"]

[tool.black]
line-length = 120
target-version = ['py310']

[tool.ruff]
line-length = 120
target-version = "py310"
indent-width = 4

[tool.isort]
profile = "black"
src_paths = ["src", "tests"]
combine_as_imports = true

[tool.pytest.ini_options]
markers = [
    "slow: marks tests as slow (deselect with '-m \"not slow\"')",
    "gpu: requires gpu",
    "multi_gpu: requires more than 1 gpu",
]