defaults:
  - /agent: student_agent  #teacher_agent # student_agent
  - override /llm@agent.llm: vllm_sft448_temp1  # vllm_llama3_8b_temp1
  - _self_

# Cannot initialize with defaults list due to multiple user simulator models
# Instead pass it as a string
user_simulator_llm: vllm_llama3_8b_temp1


num_agent_workers: 0
num_user_workers: 0
force_restart_idx: -1  # use -1 to resume from last finished layer or the layer_idx to restart from
global_count: -1

preambles_path: /mnt/llmd/data/gontiern/catalog_items/for_open_release/train/BigBankCorp
output_path: ???

layers:
- who: user
  count: 50
  probs:
    init_message_short: 4
    init_message_ask: 1
- who: agent
  count: same
- who: user
  count: same
  probs:
    ### init behaviors
    init_message_short: 2 
    init_message_ask: 1 

    ### regular behaviors
    happy_path: 6  # 10/35

    # Plausible valid user behaviors
    multislot_instruct3: 2
    skip_optional: 1

    # Asking about information
    ask_about_docs: 1

    # Invalid user behaviors
    invalid_value_3: 1 
    invalid_instruct: 1
- who: agent
  count: same
- who: user
  count: same
  probs:
    ### regular behaviors
    happy_path: 6  # 10/35

    # Plausible valid user behaviors
    multislot_instruct3: 2
    skip_optional: 1

    # Asking about information
    ask_about_docs: 1

    # Invalid user behaviors
    invalid_value_3: 1 
    invalid_instruct: 1
- who: agent
  count: same
- who: user
  count: same
  probs: same
- who: agent
  count: same
- who: user
  count: same
  probs: same
- who: agent
  count: same
- who: user
  count: same
  probs: same
- who: agent
  count: same
- who: user
  count: same
  probs: same
- who: agent
  count: same
- who: user
  count: same
  probs: same
- who: agent
  count: same
- who: user
  count: same
  probs: same
- who: agent
  count: same
