_target_: tapeagents.llms.LiteLLM
model_name: openrouter/deepseek/deepseek-chat
use_cache: false
context_size: 64000
parameters:
  temperature: 0.6
  extra_body:
    provider:
      order: ["DeepSeek"]
      allow_fallbacks: true