# https://docs.litellm.ai/docs/providers/azure#completion---using-env-variables

# Need to set these environment variables:
# AZURE_API_KEY=
# AZURE_API_BASE=
# AZURE_API_VERSION=

_target_: tapeagents.llms.LiteLLM
model_name: gpt-4o # To replace by: azure/<deployment_name>
use_cache: false
context_size: 128000
parameters:
  temperature: 0.2
