_target_: tapeagents.llms.TrainableLLM
use_cache: false
conf:
  _target_: tapeagents.llms.TrainableLLMConfig
  base_url: http://0.0.0.0:8080
  model_name: mistralai/Mixtral-8x22B-v0.1
  context_size: 8000
  request_parameters:
    temperature: 0.05
    max_tokens: 1000
