defaults:
  - _self_
  - agent: gaia_fcalls

exp_name: mcp_test_async_2
exp_path: outputs/gaia/runs/${exp_name}

llm:
  _target_: tapeagents.llms.TrainableLLM
  model_name: gpt-4o-mini-2024-07-18
  use_litellm_tokenizer_fallback: true
  use_cache: false
  context_size: 128000
  parameters:
    temperature: 0.2

environment:
  _target_: tapeagents.mcp.MCPEnvironment
  config_path: conf/mcp/web_and_code.json

split: validation
batch: 1
retry_unsolved: true

only_tasks: #[] # list of (level, task_num)
- [1, 0]
- [1, 1]
- [1, 2]
- [1, 3]
- [1, 4]
- [1, 5]
- [1, 6]
- [1, 7]

hydra:
  run:
    dir: ${exp_path}