llm:
  _target_: tapeagents.llms.LiteLLM
  model_name: chatgpt-4o-latest
  use_cache: false
  context_size: 128000
  parameters:
    temperature: 0.0

exp_name: gpt4o_demo_computer1

exp_path: outputs/gaia/runs/${exp_name}

agent:
  plain_code: false

env:
  computer_url: http://localhost:8000
  save_video: true

hydra:
  run:
    dir: ${exp_path}